import { personne as personneS1Ep1 } from "./s1/ep1/personne";
import { personne as personneS1Ep2 } from "./s1/ep2/personne";
import { personnePro as personneProS1Ep3 } from "./s1/ep3/personnePro";
import { generics as genericsS2Ep1 } from "./s2/ep1/generics";
import { generics as genericsS2Ep2 } from "./s2/ep2/generics";
import { generics as genericsS2Ep3 } from "./s2/ep3/generics";
personneS1Ep1();
personneS1Ep2();
personneProS1Ep3();
genericsS2Ep1();
genericsS2Ep2();
genericsS2Ep3();
