import { personne as personneS1Ep1 } from "./s1/ep1/personne";
import { personne as personneS1Ep2 } from "./s1/ep2/personne";
import { personnePro as personneProS1Ep3 } from "./s1/ep3/personnePro";
import { generics as genericsS2Ep1 } from "./s2/ep1/generics";
import { generics as genericsS2Ep2 } from "./s2/ep2/generics";
import { generics as genericsS2Ep3 } from "./s2/ep3/generics";
import { narrowing as narrowingS3Ep1 } from "./s3/ep1/narrowing";
import { formes as formesS3Ep2 } from "./s3/ep2/formes";
import { vehicule as vehiculeS3Ep3 } from "./s3/ep3/vehicule";
import { animaux as animauxS4Ep1 } from "./s4/ep1/animaux";
import { animaux as animauxS4Ep2 } from "./s4/ep2/animaux";
import { formes as formesS4Ep3 } from "./s4/ep3/formes";
personneS1Ep1();
personneS1Ep2();
personneProS1Ep3();
genericsS2Ep1();
genericsS2Ep2();
genericsS2Ep3();
narrowingS3Ep1();
formesS3Ep2();
vehiculeS3Ep3();
animauxS4Ep1();
animauxS4Ep2();
formesS4Ep3();
